import type { TripPlan } from "@raiquora/trip/trip-plan";

export const tripPlanPreview: TripPlan = {
  version: 1,
  id: "trip-local-preview",
  title: "温泉街と海辺をゆっくり巡る旅",
  destination: "城崎温泉",
  conditions: {
    adults: 2,
    children: 0,
    considerations: ["移動を詰め込みすぎない", "乗換を少なめにする"],
  },
  updatedAt: "2026-08-24T00:00:00.000Z",
  items: [
    {
      id: "outbound",
      type: "movement",
      mode: "rail",
      route: {
        departureDate: "2026-09-05",
        originStation: "向日町",
        destinationStation: "城崎温泉",
        journeys: [{
          departureTimeMinutes: 488,
          arrivalTimeMinutes: 681,
          transferCount: 1,
          legs: [
            {
              serviceUid: "preview-outbound-1",
              trainNumber: "128C",
              serviceType: "普通",
              trainName: "",
              serviceDestination: "京都",
              originStation: "向日町",
              destinationStation: "京都",
              departureTimeMinutes: 488,
              arrivalTimeMinutes: 496,
              lineName: "JR京都線",
              lineColor: "#0072bc",
            },
            {
              serviceUid: "preview-outbound-2",
              trainNumber: "3001M",
              serviceType: "特急",
              trainName: "きのさき1号",
              serviceDestination: "城崎温泉",
              originStation: "京都",
              destinationStation: "城崎温泉",
              departureTimeMinutes: 505,
              arrivalTimeMinutes: 681,
              lineName: "山陰線",
              lineColor: "#8fbe3c",
            },
          ],
        }],
      },
    },
    {
      id: "stay",
      type: "stay",
      destination: "城崎温泉",
      checkInDate: "2026-09-05",
      checkOutDate: "2026-09-06",
      options: [
        {
          providerItemId: "preview-hotel-1",
          name: "温泉街の小さな宿",
          areaName: "城崎温泉",
          address: "兵庫県豊岡市城崎町",
          latitude: 35.6258,
          longitude: 134.8102,
          reviewAverage: 4.4,
          reviewCount: 128,
          price: { amount: 13_200, currency: "JPY", basis: "selected-dates" },
          availability: "available",
          checkInDate: "2026-09-05",
          checkOutDate: "2026-09-06",
        },
        {
          providerItemId: "preview-hotel-2",
          name: "川沿いの旅館",
          areaName: "豊岡市",
          address: "兵庫県豊岡市城崎町湯島",
          latitude: 35.6245,
          longitude: 134.8078,
          reviewAverage: 4.1,
          reviewCount: 74,
          price: { amount: 9_800, currency: "JPY", basis: "reference-minimum" },
          availability: "unknown",
          checkInDate: "2026-09-05",
          checkOutDate: "2026-09-06",
        },
        {
          providerItemId: "preview-hotel-3",
          name: "海辺を望むホテル",
          areaName: "竹野",
          address: "兵庫県豊岡市竹野町",
          latitude: 35.6604,
          longitude: 134.7595,
          reviewAverage: 4.6,
          reviewCount: 203,
          price: { amount: 16_500, currency: "JPY", basis: "selected-dates" },
          availability: "available",
          checkInDate: "2026-09-05",
          checkOutDate: "2026-09-06",
        },
      ],
    },
    {
      id: "return",
      type: "movement",
      mode: "rail",
      route: {
        departureDate: "2026-09-06",
        originStation: "城崎温泉",
        destinationStation: "向日町",
        journeys: [{
          departureTimeMinutes: 930,
          arrivalTimeMinutes: 1_128,
          transferCount: 1,
          legs: [
            {
              serviceUid: "preview-return-1",
              trainNumber: "3018M",
              serviceType: "特急",
              trainName: "きのさき18号",
              serviceDestination: "京都",
              originStation: "城崎温泉",
              destinationStation: "京都",
              departureTimeMinutes: 930,
              arrivalTimeMinutes: 1_110,
              lineName: "山陰線",
              lineColor: "#8fbe3c",
            },
            {
              serviceUid: "preview-return-2",
              trainNumber: "247C",
              serviceType: "普通",
              trainName: "",
              serviceDestination: "西明石",
              originStation: "京都",
              destinationStation: "向日町",
              departureTimeMinutes: 1_120,
              arrivalTimeMinutes: 1_128,
              lineName: "JR京都線",
              lineColor: "#0072bc",
            },
          ],
        }],
      },
    },
  ],
};
